// <auto-generated />
using EF2_Hotel.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF2_Hotel.Migrations
{
    [DbContext(typeof(LoginContext))]
    [Migration("20240214005802_AddedTables")]
    partial class AddedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF2_Hotel.Entities.LoginEntities.Frontend", b =>
                {
                    b.Property<string>("User_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pass_word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_name");

                    b.ToTable("Frontend");
                });

            modelBuilder.Entity("EF2_Hotel.Entities.LoginEntities.Kitchen", b =>
                {
                    b.Property<string>("User_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pass_word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_name");

                    b.ToTable("Kitchens");
                });
#pragma warning restore 612, 618
        }
    }
}
